[2025-09-12T19:05:41.219+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sap_elt_pipeline.run_dbt_models manual__2025-09-12T19:04:37.849638+00:00 [queued]>
[2025-09-12T19:05:41.229+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sap_elt_pipeline.run_dbt_models manual__2025-09-12T19:04:37.849638+00:00 [queued]>
[2025-09-12T19:05:41.229+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-12T19:05:41.255+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-09-12 19:04:37.849638+00:00
[2025-09-12T19:05:41.260+0000] {standard_task_runner.py:60} INFO - Started process 9236 to run task
[2025-09-12T19:05:41.264+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sap_elt_pipeline', 'run_dbt_models', 'manual__2025-09-12T19:04:37.849638+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/sap_etl_pipeline.py', '--cfg-path', '/tmp/tmpkx1lufvi']
[2025-09-12T19:05:41.267+0000] {standard_task_runner.py:88} INFO - Job 48: Subtask run_dbt_models
[2025-09-12T19:05:41.320+0000] {task_command.py:423} INFO - Running <TaskInstance: sap_elt_pipeline.run_dbt_models manual__2025-09-12T19:04:37.849638+00:00 [running]> on host f99cf7ca5f05
[2025-09-12T19:05:41.426+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sap_elt_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T19:04:37.849638+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-12T19:04:37.849638+00:00'
[2025-09-12T19:05:41.428+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-12T19:05:41.429+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --project-dir /opt/***/dbt --profiles-dir /opt/***/dbt']
[2025-09-12T19:05:41.443+0000] {subprocess.py:86} INFO - Output:
[2025-09-12T19:05:43.560+0000] {subprocess.py:93} INFO - [0m19:05:43  Running with dbt=1.9.0-b2
[2025-09-12T19:05:43.563+0000] {subprocess.py:93} INFO - [0m19:05:43  [[33mWARNING[0m]: Deprecated functionality
[2025-09-12T19:05:43.564+0000] {subprocess.py:93} INFO - 
[2025-09-12T19:05:43.565+0000] {subprocess.py:93} INFO - User config should be moved from the 'config' key in profiles.yml to the 'flags' key in dbt_project.yml.
[2025-09-12T19:05:45.077+0000] {subprocess.py:93} INFO - [0m19:05:45  Registered adapter: snowflake=1.8.0
[2025-09-12T19:05:45.827+0000] {subprocess.py:93} INFO - [0m19:05:45  Found 5 models, 5 sources, 453 macros
[2025-09-12T19:05:45.832+0000] {subprocess.py:93} INFO - [0m19:05:45
[2025-09-12T19:05:45.834+0000] {subprocess.py:93} INFO - [0m19:05:45  Concurrency: 4 threads (target='dev')
[2025-09-12T19:05:45.835+0000] {subprocess.py:93} INFO - [0m19:05:45
[2025-09-12T19:05:49.607+0000] {subprocess.py:93} INFO - [0m19:05:49
[2025-09-12T19:05:49.608+0000] {subprocess.py:93} INFO - [0m19:05:49  Finished running  in 0 hours 0 minutes and 3.77 seconds (3.77s).
[2025-09-12T19:05:49.609+0000] {subprocess.py:93} INFO - [0m19:05:49  Encountered an error:
[2025-09-12T19:05:49.610+0000] {subprocess.py:93} INFO - Database Error
[2025-09-12T19:05:49.610+0000] {subprocess.py:93} INFO -   003001 (42501): SQL access control error:
[2025-09-12T19:05:49.611+0000] {subprocess.py:93} INFO -   Insufficient privileges to operate on database 'SAP_ANALYTICS_DB'.
[2025-09-12T19:05:49.947+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-09-12T19:05:49.959+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-09-12T19:05:49.964+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=sap_elt_pipeline, task_id=run_dbt_models, execution_date=20250912T190437, start_date=20250912T190541, end_date=20250912T190549
[2025-09-12T19:05:49.991+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 48 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 2.; 9236)
[2025-09-12T19:05:50.001+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-12T19:05:50.032+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
