[2025-08-31T17:56:45.481+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: snowflake_connection_test.test_snowflake_connection manual__2025-08-31T17:56:41.710258+00:00 [queued]>
[2025-08-31T17:56:45.500+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: snowflake_connection_test.test_snowflake_connection manual__2025-08-31T17:56:41.710258+00:00 [queued]>
[2025-08-31T17:56:45.501+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-31T17:56:45.618+0000] {taskinstance.py:2191} INFO - Executing <Task(SnowflakeOperator): test_snowflake_connection> on 2025-08-31 17:56:41.710258+00:00
[2025-08-31T17:56:45.641+0000] {standard_task_runner.py:60} INFO - Started process 1518 to run task
[2025-08-31T17:56:45.660+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'snowflake_connection_test', 'test_snowflake_connection', 'manual__2025-08-31T17:56:41.710258+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/snowflake_connection_test_dag.py', '--cfg-path', '/tmp/tmpm8de86ea']
[2025-08-31T17:56:45.669+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask test_snowflake_connection
[2025-08-31T17:56:45.884+0000] {task_command.py:423} INFO - Running <TaskInstance: snowflake_connection_test.test_snowflake_connection manual__2025-08-31T17:56:41.710258+00:00 [running]> on host ea85b8cb7b29
[2025-08-31T17:56:46.172+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='snowflake_connection_test' AIRFLOW_CTX_TASK_ID='test_snowflake_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-08-31T17:56:41.710258+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-31T17:56:41.710258+00:00'
[2025-08-31T17:56:46.178+0000] {sql.py:276} INFO - Executing: SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();
[2025-08-31T17:56:46.211+0000] {base.py:83} INFO - Using connection ID 'snowflake_default' for task execution.
[2025-08-31T17:56:46.244+0000] {base.py:83} INFO - Using connection ID 'snowflake_default' for task execution.
[2025-08-31T17:56:46.246+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.8.18, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.34
[2025-08-31T17:56:46.250+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-08-31T17:56:48.645+0000] {cursor.py:1028} INFO - query: [ALTER SESSION SET autocommit=False]
[2025-08-31T17:56:48.938+0000] {cursor.py:1041} INFO - query execution done
[2025-08-31T17:56:48.940+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2025-08-31T17:56:48.942+0000] {sql.py:450} INFO - Running statement: SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();, parameters: None
[2025-08-31T17:56:48.944+0000] {cursor.py:1028} INFO - query: [SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), ...]
[2025-08-31T17:56:49.249+0000] {cursor.py:1041} INFO - query execution done
[2025-08-31T17:56:49.253+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2025-08-31T17:56:49.255+0000] {sql.py:459} INFO - Rows affected: 1
[2025-08-31T17:56:49.283+0000] {snowflake.py:400} INFO - Rows affected: 1
[2025-08-31T17:56:49.285+0000] {snowflake.py:401} INFO - Snowflake query id: 01bebe14-0106-5340-0010-1bf3000170da
[2025-08-31T17:56:49.287+0000] {cursor.py:1028} INFO - query: [COMMIT]
[2025-08-31T17:56:49.599+0000] {cursor.py:1041} INFO - query execution done
[2025-08-31T17:56:49.601+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2025-08-31T17:56:49.604+0000] {connection.py:718} INFO - closed
[2025-08-31T17:56:49.926+0000] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2025-08-31T17:56:50.373+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=snowflake_connection_test, task_id=test_snowflake_connection, execution_date=20250831T175641, start_date=20250831T175645, end_date=20250831T175650
[2025-08-31T17:56:50.470+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-31T17:56:50.575+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
