[2025-09-01T16:02:39.518+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sap_elt_pipeline.run_dbt_models manual__2025-09-01T16:02:09.183508+00:00 [queued]>
[2025-09-01T16:02:39.527+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sap_elt_pipeline.run_dbt_models manual__2025-09-01T16:02:09.183508+00:00 [queued]>
[2025-09-01T16:02:39.528+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-01T16:02:39.543+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-09-01 16:02:09.183508+00:00
[2025-09-01T16:02:39.548+0000] {standard_task_runner.py:60} INFO - Started process 817 to run task
[2025-09-01T16:02:39.552+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sap_elt_pipeline', 'run_dbt_models', 'manual__2025-09-01T16:02:09.183508+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/sap_etl_pipeline.py', '--cfg-path', '/tmp/tmp1_oonysa']
[2025-09-01T16:02:39.554+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask run_dbt_models
[2025-09-01T16:02:39.605+0000] {task_command.py:423} INFO - Running <TaskInstance: sap_elt_pipeline.run_dbt_models manual__2025-09-01T16:02:09.183508+00:00 [running]> on host 4b0b367b7a67
[2025-09-01T16:02:39.713+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sap_elt_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T16:02:09.183508+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-01T16:02:09.183508+00:00'
[2025-09-01T16:02:39.716+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-01T16:02:39.717+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --project-dir /opt/***/dbt']
[2025-09-01T16:02:39.727+0000] {subprocess.py:86} INFO - Output:
[2025-09-01T16:02:43.285+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2025-09-01T16:02:43.286+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2025-09-01T16:02:43.286+0000] {subprocess.py:93} INFO - 
[2025-09-01T16:02:43.288+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/home/***/.dbt' does not exist.
[2025-09-01T16:02:43.488+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-09-01T16:02:43.527+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-09-01T16:02:43.548+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=sap_elt_pipeline, task_id=run_dbt_models, execution_date=20250901T160209, start_date=20250901T160239, end_date=20250901T160243
[2025-09-01T16:02:43.602+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 2.; 817)
[2025-09-01T16:02:43.626+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-01T16:02:43.666+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
